### ISSUE TITLE
[LAB-13] Swiper 라이브러리 사용 시, 이미지 조절 깨짐 문제

### ISSUE THREAD

**Issue by ddengmin** [yamoo9/likelion-FEQA#155]
## 질문 작성자

최영민

## 문제 상황
![스와이퍼 오류](https://user-images.githubusercontent.com/82636319/225352000-837862b5-2576-479c-beb4-fda5ace9f83d.gif)
안녕하세요.
타잉 사이트 메인 나브바 페이지 중 메인 슬라이더(티빙에만 있는 재미) 부분을 스와이퍼 라이브러리를 사용해 제작하는 중 문제가 생겨 질문 남깁니다.
스와이퍼 기능 중 Navigation, Pagination, Scrollbar 를 사용했으나, 이미지 조절을 따로 안했음에도 불구하고 
이미지 조절이 깨짐 문제가 발생했습니다.
스와이퍼 이미지 하나만 나오게 이미지 크기 조절할 수 있는 방법을 여쭤보고 싶어서 이슈에 올립니다!

## 프로젝트 저장소 URL

- github push 전 상태라 이미지로 대체해서 올립니다.
<img width="953" alt="image" src="https://user-images.githubusercontent.com/82636319/225359654-85ff591b-c9b9-4a9c-b3ee-73365c216ad8.png">
-jsx

<img width="789" alt="image" src="https://user-images.githubusercontent.com/82636319/225359962-c4e5699f-c40b-4e5f-bc30-30475c4fd29e.png">
<img width="850" alt="image" src="https://user-images.githubusercontent.com/82636319/225360197-186cfc70-a439-4013-b213-97cc33ca257f.png">
<img width="463" alt="image" src="https://user-images.githubusercontent.com/82636319/225360281-9dbbf658-3da3-4d31-b906-77db85eebe3e.png">

-css

- 트러블 슈팅을 위해 `node_modules` 폴더를 제외한 나머지를 압축해 이 곳에 첨부하세요.
- [issue.zip](https://github.com/yamoo9/likelion-FEQA/files/10981866/issue.zip)

## 환경 정보

- macOS
- 라이브러리 정보 ("swiper": "9.1.0")

**Comment by yamoo9** [comment]
## ⚠️ GitHub Push 전 상태라 이미지로 대체해서 올립니다.

스크란샷 이미지만으로 문제 확인이 가능하지 않습니다. 
문제 상황을 직접 보지 않고, 머리 속 시뮬레이션 만으로 답변할 수 있는 문제가 아닙니다.

## 문제 상황

첨부된 issue.zip 파일을 다운로드 받아 테스트 하려 했으나, 문제 상황이 재현되지 않네요.

> 스와이퍼 기능 중 Navigation, Pagination, Scrollbar 를 사용했으나, 이미지 조절을 따로 안 했음에도 불구하고 이미지 조절이 깨짐 문제가 발생했습니다. 스와이퍼 이미지 하나만 나오게 이미지 크기 조절할 수 있는 방법을 여쭤보고 싶어서 이슈에 올립니다!

## 문제 상황 재현

임의로 문제 상황을 재현해 SwiperSlide 콘텐츠가 1개만 표시되도록 구현했습니다.

![](https://user-images.githubusercontent.com/1850554/225458155-3ebc871f-4ced-44de-8cca-1a0cb24a4f59.gif)

<img width="1920" alt="" src="https://user-images.githubusercontent.com/1850554/225457412-31cf94a6-b45d-4646-9a4c-a79c4a18c4a9.png">

<details open>
  <summary>MainNavPage.jsx</summary>

  ```jsx
  import { Swiper, SwiperSlide } from 'swiper/react';
  import { Navigation, Pagination, Scrollbar, A11y } from 'swiper';
  
  import 'swiper/swiper.css';
  import 'swiper/css/navigation';
  import 'swiper/css/pagination';
  import 'swiper/css/scrollbar';
  import style from './MainNavPage.module.css';
  
  import slideImage1 from '../../assets/images/maknaeadeul_01.jpg';
  import slideImage2 from '../../assets/images/bodyvalue_03.jpg';
  
  export default function App() {
    const slides = [
      {
        id: 'slide-1',
        image: slideImage1,
        description: '인생 1회차를 사는 판타지 드라마',
        link: '/sample/1',
      },
      {
        id: 'slide-2',
        image: slideImage2,
        description: '인생 2회차를 사는 판타지 드라마',
        link: '/sample/2',
      },
    ];
  
    return (
      <div className={style.container}>
        <Swiper
          modules={[Navigation, Pagination, Scrollbar, A11y]}
          slidesPerView={1}
          spaceBetween={0}
          speed={400}
          loop
          navigation
          pagination={{ clickable: true }}
          scrollbar={{ draggable: true }}
          className={style.swiper}
        >
          {slides.map(slide => (
            <SwiperSlide key={slide.id} className={style.swiperSlide}>
              <img src={slide.image} alt="" />
              <div className="contents">
                <p className="contents-text">{slide.description}</p>
                <div className="contents-button">
                  <a href={slide.link}>자세히 보기</a>
                </div>
              </div>
            </SwiperSlide>
          ))}
        </Swiper>
      </div>
    );
  }
  ```
</details>

<details>
  <summary>MainNavPage.module.css</summary>

  ```css
  .container {
    box-sizing: border-box;
    padding: 20px;
  }
  
  .container * {
    box-sizing: inherit;
  }
  
  .swiper {
    width: 100%;
    height: calc(100vh - 40px);
    background: #010101;
  }
  
  .swiper div[role="button"] {
    color: rgba(255, 255, 255, 0.4);
    transition: all 0.6s;
  }
  
  .swiper div[role="button"]:hover {
    color: rgba(255, 255, 255, 1);
  }
  
  .swiper span[role="button"] {
    background: rgba(255, 255, 255, 0.8);
    transition: all 0.6s;
  }
  
  .swiper span[role="button"]:hover {
    background: rgba(255, 255, 255, 1);
  }
  
  .swiperSlide {
    -webkit-transform: translateZ(0);
  }
  
  .swiperSlide img {
    width: 100%;
    height: 100%;
    object-fit: contain;
  }
  
  @media (min-width: 960px) {
    .swiperSlide img {
      object-fit: cover;
    }
  }
  ```
</details>

<br />
