### ISSUE TITLE
[LAB-13] 호버했을때 스와이퍼 화살표가 보이는 코드를 짜던중 고민이 생겨 이슈 남깁니다.

### ISSUE THREAD

**Issue by kyoungholee** [yamoo9/likelion-FEQA#161]
## 질문 작성자

이경호

## 문제 상황

1.  현재 스와이퍼에 화살표가 평소에는 안보였다가 마우스를 호버 했을 때 화살표가 보이게 하는 기능을 구현하고 있습니다.

문제 1 : useRef를 사용해서 평소에는 current 값을 null 로 처리하고, 마우스가 호버 했을 때 current 값을 undefined로 변경 할 수 있게 코드를 작성하였습니다.
하지만 작동하지 않는 거 같습니다. 제가 생각하는 이유는 ~? useRef를 쓰게 되면 값이 변경은 되나 렌더링이 되기 전까지는 그 값이 화면에 반영되지 않는 걸로 알고 있어서 화살표가 보이지 않는 것으로 생각합니다.

============> 이럴 떄는 어떻게 해야 할까요? 
시도해본 것 : 의미없는 state 값을 넣어서 상태 변경을 해주었습니다.  이럴 떄 화살표는 보이나 슬라이드 기능이 작동하지 않는 거 같습니다. 

문제2. 2번째로 생각한 방법은 useRef가 아닌 state를 이용해 상태관리를 해봤습니다.
마우스를 호버할때마다 state 값이 undefined로 바뀔 수 있게 코드 작성을 해보았지만 이것 또 한 기능을 잘 되지만 화살표에 역할을 하지 못했습니다.

좋은 방법이 있을까요? 
useEffect를 사용해서 코드를 작성해야 할까요? 

![그럼 1](https://user-images.githubusercontent.com/65242726/225797523-1c7735f2-58db-4135-adc3-34b7d55b8e36.PNG)

![그림 2](https://user-images.githubusercontent.com/65242726/225797540-09b56741-b5a4-4511-95b6-d95ac5d69abd.PNG)

![gg](https://user-images.githubusercontent.com/65242726/225797885-7fa0d06d-cd4c-40fc-a7f6-6c4efccd787f.PNG)

## 프로젝트 저장소 URL

- 공개된 GitHub 프로젝트 저장소 URL을 여기에 남깁니다.
- main 브랜치가 아닐 경우, 확인해야 할 브랜치 이름도 함께 작성합니다.
- 트러블 슈팅을 위해 `node_modules` 폴더를 제외한 나머지를 압축해 이 곳에 첨부하세요.

## 환경 정보

- 운영체제 정보 (예: Windows, macOS)
- Node.js 정보 (예: v16.14.0)
- 라이브러리 정보 (예: React v18.0.2)

**Comment by yamoo9** [comment]
## 문제 검토

@kyoungholee 님 🤔
저장소 브랜치와 봐야 할 파일 위치를 함께 알려주시면 검토한 후 답변 드릴께요.

**Comment by kyoungholee** [comment]
https://github.com/kyoungholee/LAB13-PROJECT/blob/feature/kyoungho/mainpage-MainPageSlide/src/pages/MainPageSlide/MainPageSlide.jsx

**Comment by yamoo9** [comment]
## 문제 검토

@kyoungholee 님. 너무 복잡하지 않게 생각할 때, 오히려 문제가 쉽게 해결될 수 있습니다. 😃

![](https://user-images.githubusercontent.com/1850554/225886534-6f63e5ec-70a4-4def-9c89-b730a24bc1d1.gif)

문제 해결 방법은 CSS를 활용하는 것입니다. CSS만으로도 충분하게 컨트롤 가능합니다. 

<img width="1683" alt="" src="https://user-images.githubusercontent.com/1850554/225885066-46fecc02-2b16-4366-9f22-47338d14318b.png">

아래 작성한 코드를 첨부합니다. 확인 검토해보세요. 😌

<details open>
  <summary>MainPageSlide.jsx</summary>

  ```jsx
  export default function MainPageSlide() {
    const { id = 4 } = useParams();
  
    const [num, setNum] = useState(1);
  
    const { readData, data, isLoading, error } = useReadData('image');
  
    async function handleReadData() {
      // 모든 데이터를 가져옵니다.
      await readData();
  
      // 또는 특정 도큐멘트 데이터만 가져옵니다.
      await readData();
    }
  
    return (
      <>
        <div className={style.mainBanner}>메인 배너 들어갈 자리 </div>
        <div className="contanier-title">
          <h2
            style={{ marginLeft: '60px', marginBottom: '8px' }}
            className={style.list_title}
          >
            티빙에서 꼭 봐야하는 콘텐츠
          </h2>
  
          <Swiper
            style={{ marginBottom: '36px' }}
            spaceBetween={10}
            slidesPerView={7.2}
            slidesPerGroup={6}
            navigation
          >
            {/* ... */}
        </div>
      </>
    );
  }
  ```
</details>

<details>
  <summary>MainPageSlide.css</summary>

  ```css
  .swiper .swiper-button-prev::after,
  .swiper .swiper-button-next::after {
    margin-bottom: 60px;
    color: #e1e1e1;
  }
  
  .swiper-slide div {
    margin-top: 10px;
    transition: all 0.2s linear;
  }
  
  .swiper-slide:hover div {
    transform: translate(0px, -10px);
  }
  
  
  .swiper div[role="button"] {
    opacity: 0;
    transition: all 0.3s ease-in-out;
  }
  
  .swiper:hover div[role="button"],
  .swiper:focus-within div[role="button"] {
    opacity: 1;
  }
  ```
</details>

<br />
